#!/usr/bin/env python3
"""Validate Grafana dashboards and generate sidecar-loadable ConfigMaps.

Validation keeps dashboards honest: every ``inference_gateway_*`` or ``rag_service_*``
series used in a panel query must be a metric the service actually emits, so renaming or
removing a metric without updating its dashboard fails the check.

``--write`` renders ``observability/dashboards/configmap.yaml`` from the canonical dashboard
JSON. Each dashboard becomes a ConfigMap labelled ``grafana_dashboard: "1"`` so the Grafana
sidecar (shipped by kube-prometheus-stack) auto-loads it. ``--check`` fails when that rendered
file drifts from the dashboards, keeping the provisioned copies in sync with their sources.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_DIR = ROOT / "observability/dashboards"
CONFIGMAP_PATH = DASHBOARD_DIR / "configmap.yaml"
DASHBOARD_NAMESPACE = "monitoring"
REQUIRED_DASHBOARDS = (
    "inference-dashboard.json",
    "rag-dashboard.json",
    "restore-drill-dashboard.json",
)
METRIC_PATTERN = re.compile(r"(?:inference_gateway|rag_service)_[a-z0-9_]+")
HISTOGRAM_SUFFIXES = ("_bucket", "_sum", "_count")
SERVICE_SOURCES = {
    "inference_gateway": ROOT / "src/inference-gateway/app",
    "rag_service": ROOT / "src/rag-service/app",
}


class _LiteralStr(str):
    """Marker type rendered as a YAML literal block scalar."""


def _literal_representer(dumper: yaml.SafeDumper, data: _LiteralStr) -> yaml.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:str", str(data), style="|")


yaml.SafeDumper.add_representer(_LiteralStr, _literal_representer)


def require(errors: list[str], condition: bool, message: str) -> None:
    if not condition:
        errors.append(message)


def service_metric_names(prefix: str) -> set[str]:
    names: set[str] = set()
    for path in SERVICE_SOURCES[prefix].glob("*.py"):
        names.update(re.findall(rf"{prefix}_[a-z0-9_]+", path.read_text(encoding="utf-8")))
    return names


def base_metric_name(metric: str) -> str:
    for suffix in HISTOGRAM_SUFFIXES:
        if metric.endswith(suffix):
            return metric[: -len(suffix)]
    return metric


def collect_exprs(panels: list[dict]) -> list[str]:
    return [
        target["expr"]
        for panel in panels
        for target in panel.get("targets", [])
        if isinstance(target, dict) and target.get("expr")
    ]


def dashboard_files() -> list[Path]:
    return sorted(path for path in DASHBOARD_DIR.glob("*.json"))


def render_configmaps() -> str:
    """Render the canonical dashboards as Grafana-sidecar ConfigMap manifests."""
    documents = []
    for path in dashboard_files():
        name = path.stem
        manifest = {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {
                "name": f"grafana-dashboard-{name}",
                "namespace": DASHBOARD_NAMESPACE,
                "labels": {
                    "grafana_dashboard": "1",
                    "app.kubernetes.io/part-of": "private-ai-platform-kit",
                },
            },
            "data": {f"{name}.json": _LiteralStr(path.read_text(encoding="utf-8"))},
        }
        documents.append(yaml.safe_dump(manifest, sort_keys=True, default_flow_style=False))
    header = "# Generated by scripts/dashboard-check.py --write. Do not edit by hand.\n"
    return header + "---\n" + "---\n".join(documents)


def check_dashboards() -> list[str]:
    errors: list[str] = []
    require(errors, DASHBOARD_DIR.is_dir(), "observability/dashboards directory must exist")
    for name in REQUIRED_DASHBOARDS:
        require(errors, (DASHBOARD_DIR / name).is_file(), f"required dashboard missing: {name}")

    known_metrics = service_metric_names("inference_gateway") | service_metric_names("rag_service")

    for path in dashboard_files():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"{path.name}: invalid JSON: {exc}")
            continue
        require(errors, isinstance(data, dict), f"{path.name}: dashboard must be a JSON object")
        if not isinstance(data, dict):
            continue
        require(errors, bool(data.get("title")), f"{path.name}: dashboard must set a title")
        require(errors, bool(data.get("uid")), f"{path.name}: dashboard must set a uid")
        panels = data.get("panels")
        require(errors, isinstance(panels, list) and bool(panels), f"{path.name}: dashboard must define panels")
        if not isinstance(panels, list):
            continue
        exprs = collect_exprs(panels)
        require(errors, bool(exprs), f"{path.name}: dashboard must define at least one panel query")
        for expr in exprs:
            for metric in METRIC_PATTERN.findall(expr):
                base = base_metric_name(metric)
                require(errors, base in known_metrics, f"{path.name}: query references unknown platform metric '{base}'")

    rendered = render_configmaps()
    require(errors, CONFIGMAP_PATH.is_file(), f"missing generated {CONFIGMAP_PATH.relative_to(ROOT)}; run --write")
    if CONFIGMAP_PATH.is_file() and CONFIGMAP_PATH.read_text(encoding="utf-8") != rendered:
        errors.append(
            f"{CONFIGMAP_PATH.relative_to(ROOT)} is stale; run scripts/dashboard-check.py --write"
        )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate Grafana dashboards and render provisioning ConfigMaps.")
    parser.add_argument("--check", action="store_true", help="Validate dashboards and provisioning ConfigMaps.")
    parser.add_argument("--write", action="store_true", help="Write the dashboard provisioning ConfigMaps.")
    args = parser.parse_args()
    if not args.check and not args.write:
        args.check = True

    if args.write:
        CONFIGMAP_PATH.write_text(render_configmaps(), encoding="utf-8")
        print(f"wrote {CONFIGMAP_PATH.relative_to(ROOT)}")

    if args.check:
        errors = check_dashboards()
        if errors:
            print("dashboard check failed:")
            for error in errors:
                print(f"- {error}")
            return 1
        print(f"dashboards ok ({len(REQUIRED_DASHBOARDS)} required dashboards validated and provisioned)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
