apiVersion: v1
kind: Secret
metadata:
  name: ai-platform-local-seed
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: local-secret-seed
    app.kubernetes.io/part-of: ai-platform-ops-lab
type: Opaque
stringData:
  gateway-api-key: local-development-only
  api-key-sha256s: ed20191044553dac8f9c45e62062dd18e7dc1f898a897240b4179fb84fea3db4
  restore-drill-webhook-token: local-development-only
  hf-token: local-development-only
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-kubernetes-store
  namespace: inference
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inference-gateway-secrets
  namespace: inference
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-kubernetes-store
    kind: SecretStore
  target:
    name: inference-gateway-secrets
  data:
    - secretKey: gateway-api-key
      remoteRef:
        key: ai-platform-local-seed
        property: gateway-api-key
    - secretKey: api-key-sha256s
      remoteRef:
        key: ai-platform-local-seed
        property: api-key-sha256s
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-kubernetes-store
  namespace: rag
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-service-secrets
  namespace: rag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-kubernetes-store
    kind: SecretStore
  target:
    name: rag-service-secrets
  data:
    - secretKey: api-key-sha256s
      remoteRef:
        key: ai-platform-local-seed
        property: api-key-sha256s
