apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-ops-lab-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: ai-platform-ops-lab-root
    app.kubernetes.io/part-of: ai-platform-ops-lab
spec:
  project: default
  source:
    repoURL: https://github.com/RamazanKara/ai-platform-ops-lab.git
    targetRevision: HEAD
    path: clusters/local
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

